const texts = {
  en: {
    appTitle: 'Divination',
    bannerAlt: 'The Moon',
    daysLabel: 'Days',
    desc: 'Get the weather for any city in the World!',
    dismiss: 'dismiss',
    currentPosition: 'Your current location',
    feelsLikeLabel: 'Feels Like',
    findCity: 'Find a city.',
    getWeather: 'OK',
    humidityLabel: 'Humidity',
    iconFallbackAlt: 'No weather info',
    maxTempLabel: 'High',
    minTempLabel: 'Low',
    or: 'Or',
    popLabel: 'Probability of precipitation',
    rain: 'rain',
    snow: 'snow',
    tempLabel: 'Temperature',
    useLocation: 'use your current location',
    weekForecastLabel: '7-day forecast',
    wind: 'wind',
    worldComment: 'Beautiful',
    worldMap: 'Map of the World'
  },
  fr: {
    appTitle: 'Divination',
    bannerAlt: 'La Lune',
    daysLabel: 'Jours',
    desc: 'Trouvez la météo, où que vous soyez!',
    dismiss: 'fermer',
    currentPosition: 'Votre position actuelle',
    feelsLikeLabel: 'Ressenti',
    findCity: 'Trouver une ville',
    getWeather: 'OK',
    humidityLabel: 'Humidité',
    iconFallbackAlt: 'Aucune info météo',
    maxTempLabel: 'Maximum',
    minTempLabel: 'Minimum',
    or: 'Ou',
    popLabel: 'Probabilité de précipitation',
    rain: 'pluie',
    snow: 'neige',
    tempLabel: 'Température',
    useLocation: 'utiliser votre position actuelle',
    weekForecastLabel: 'Prévisions sur 7 jours',
    wind: 'vent',
    worldComment: 'Magnifique',
    worldMap: 'Carte du Monde'
  }
}

export default texts
